### ISSUE TITLE
Why do not use Loki?

### ISSUE THREAD

**Issue by denisgolius** [BigKAA/metrics-from-logs#5]
Why do not use Loki?

Loki support PromQL queries and yes Loki's documentation is not update frequently but we have https://t.me/ru_loki in telegram that helps to improve skill it it.

**Comment by BigKAA** [comment]
Because we have been using ElastiskSearch for a long time. To transfer all our systems to Loki will require large resources.

**Comment by BigKAA** [comment]
Не по теме

**Comment by denisgolius** [comment]
> Не по теме

ИМХО: как вы круто описываете причину, вам явно светит прекрасное будущее в open source, не понятно только, зачем наваливать людям в примеры то, что было у вас но не делать обзор того, что есть и что популярное? При этом довольно не плохо работает.

**Comment by BigKAA** [comment]
> > Не по теме
> 
> ИМХО: как вы круто описываете причину, вам явно светит прекрасное будущее в open source, не понятно только, зачем наваливать людям в примеры то, что было у вас но не делать обзор того, что есть и что популярное? При этом довольно не плохо работает.

Честно говоря я не понял причины вашего наезда. При чем тут использую ли я Loki и конкретное приложение? Какое отношение имеет loki к metrics-from-logs ? Почему я должен делать обзор loki в исходных кодах приложения, работающего совсем с другой системой?

Ваше issue не имеет никакого отношения к данному приложению.
